# This is a basic workflow to help you get started with Actions

name: Automaçao WEB

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]
        
      # Checkout  do codigo do projeto
      - name: Checkout
        uses: actions/checkout@v2 

      # Setup do Node.JS
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}

      # Dependecies install
      - name: Install dependecies
        run: |
          sudo apt-get install google-chrome-stable
          npm install

      # Regression test execute Android
      - name: Run tests Android
        run: |
          npx codeceptjs run

