on:
  push:
    branches:
    - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: |
          npx playwright install-deps
          npx playwright install-deps chromium
          npm install 
          npx codeceptjs run
